# Generated by Django 3.1.7 on 2021-10-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
