# Generated by Django 3.2.8 on 2021-10-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_weather_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='lattitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
